"""Criação das novas tabelas do Banco de Dados

Revision ID: e1563c4fb562
Revises: 9ef0630d49ed
Create Date: 2025-04-26 18:08:12.551648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1563c4fb562'
down_revision = '9ef0630d49ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=175), nullable=False),
    sa.Column('senha', sa.String(length=10), nullable=False),
    sa.Column('nome_usuario', sa.String(length=30), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('endereco_rua', sa.String(length=255), nullable=True),
    sa.Column('endereco_numero', sa.String(length=10), nullable=True),
    sa.Column('endereco_cidade', sa.String(length=100), nullable=True),
    sa.Column('endereco_estado', sa.String(length=50), nullable=True),
    sa.Column('endereco_cep', sa.String(length=10), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome_usuario')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('raca', sa.String(length=30), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=6), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servico', sa.String(length=100), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento_hotel_pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('data_check_in', sa.DateTime(), nullable=True),
    sa.Column('data_check_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento_tosa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_tosa', sa.String(length=100), nullable=True),
    sa.Column('data_tosa', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento_uber_pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('endereco_origem', sa.String(length=255), nullable=True),
    sa.Column('endereco_destino', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento_vacinacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_vacina', sa.String(length=100), nullable=True),
    sa.Column('data_vacinacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('usuarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=175), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=10), nullable=False),
    sa.Column('nome_usuario', sa.VARCHAR(length=30), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=11), nullable=True),
    sa.Column('endereco_rua', sa.VARCHAR(length=255), nullable=True),
    sa.Column('endereco_numero', sa.VARCHAR(length=10), nullable=True),
    sa.Column('endereco_cidade', sa.VARCHAR(length=100), nullable=True),
    sa.Column('endereco_estado', sa.VARCHAR(length=50), nullable=True),
    sa.Column('endereco_cep', sa.VARCHAR(length=10), nullable=True),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.Column('tipo_usuario', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome_usuario')
    )
    op.drop_table('agendamento_vacinacao')
    op.drop_table('agendamento_uber_pet')
    op.drop_table('agendamento_tosa')
    op.drop_table('agendamento_hotel_pet')
    op.drop_table('agendamento')
    op.drop_table('pet')
    op.drop_table('usuario')
    # ### end Alembic commands ###
